title: Minimal theme
logo: /assets/img/logo.png
description: Graduate in Computer Graphics and Multimedia
Post-graduate degree in information systems 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
