title: Minimal theme
logo: /assets/img/cara.jpg
description: Graduate in Computer Graphics and Multimedia <br> <br> Post-graduate degree in information systems <br> <br> <a href="https://www.linkedin.com/in/joselopes96/">View my LinkedIn Profile</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
