title: Minimal theme
logo: /assets/img/logo.png
description: > Minimal is a theme for GitHub Pages.
<br><br>
Graduate in Computer Graphics and Multimedia
Post-graduate degree in information systems 
google_analytics:
theme: jekyll-theme-minimal
